[package]
name = "update_agent"
version = "0.1.0"
authors = ["Adam Gashlin <agashlin@mozilla.com>"]
license = "MPL-2.0"

[lib]
path = "src/lib.rs"
name = "update_agent"

[[bin]]
path = "src/main.rs"
name = "update_agent"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
bits = { path = "./bits", features = [ "status_serde" ] }
bincode = "1.0.1"
comedy = { path = "./comedy", features = [ "guid_serde" ] }
failure = "0.1.4"
named_pipe = { path = "./named_pipe" }
serde = "1.0.80"
serde_derive = "1.0.80"
task_service = { path = "./task_service" }

[dev-dependencies]
winapi = { version = "0.3.6", features = [ "bits" ] }
